### ISSUE TITLE
Incompatible types found for T regression

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#6334]
Regression introduced by https://github.com/vimeo/psalm/commit/acc7ee261c106b4ae91f333ff4a9939b6e858bf3

https://psalm.dev/r/7ef9325f16

The real-life version of this involves unwrapping a (potentially wrapped in another generator) return type of a generator.
