### ISSUE TITLE
[Templating] assertig that a `string` is `non-empty-string` using a generic validator results in a *false* redundant condition error

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#6573]
example: https://psalm.dev/r/ae244c6b02

If we replace `Type<non-empty-string>` with a concrete class, we get no issues: https://psalm.dev/r/515024a452

investigating further, this seems to be related to `covariant` templating: https://psalm.dev/r/b0278b0493

whatever psalm changed in 4.10, completely broke PSL Type component, we now have the choice to either go back to using `@template` and not be able to create a union type, and any other array type, or keep as is and remove `matches` validator ( both options are BC breaking, currently  down stream users are getting a type error either in the constructor ( for PSL < 1.8 ), or when using `matches` ( PSL  >= 1.8, which uses  `covariant`  )

ref: https://github.com/azjezz/psl/issues/227
ref: https://github.com/azjezz/psl/discussions/231
ref: https://github.com/azjezz/psl/issues/212
ref: https://github.com/azjezz/psl/pull/214

**Comment by bendavies** [comment]
Nice investigation. Thanks!

**Comment by orklah** [comment]
I went back to january but this snippet still produced the same error with Psalm's code.

Are you sure this is related with Psalm 4.10 specifically?

**Comment by azjezz** [comment]
@orklah not sure which psalm version exactly broke this, but in February when matches() was introduced, and we where using `@template`, psalm didn't result in any errors: https://github.com/azjezz/psl/tree/feature/type/vec%2Bdict ( i restored the branch if you would like to test it )

**Comment by orklah** [comment]
Not sure what I should look at, there's a lot of Psalm errors in the CI for this branch.
However, if you say this was working in February, could you create a snippet that would fail in 4.10 and that would pass in 4.4.1 (release from January)?

**Comment by azjezz** [comment]
This works in 4.4.1, and fails in 4.10: https://psalm.dev/r/5aee8f5518

**Comment by orklah** [comment]
Oh, so this is related to the 'Incompatible types found for" error.

For reference, here are similar issues:
https://github.com/vimeo/psalm/issues/6277
https://github.com/vimeo/psalm/issues/6288
https://github.com/vimeo/psalm/issues/6212

and it seems it was introduced by Matt refactoring some code here: https://github.com/vimeo/psalm/commit/acc7ee261c106b4ae91f333ff4a9939b6e858bf3

He made some fix for one case here: https://github.com/vimeo/psalm/commit/a205a23ccb855aa7def01b9051d7c6a592df6fd3

and there was some explanation here: https://github.com/vimeo/psalm/issues/6073#issuecomment-886269578

It's well above my current knowledge of Psalm though...

**Comment by azjezz** [comment]
I think the covariant issue is not a problem, however, i also don't think `matches` should fail in this case, i will try to give it a try and fix it :)

**Comment by azjezz** [comment]
If it helps, here's the script i'm using for testing/debugging: 

```
<?php

/**
 * @template-covariant T
 */
interface Type {
    /**
     * @param mixed $value
     *
     * @psalm-assert-if-true T $value
     */
    public function matches($value): bool;
}

/**
 * @template-implements Type<non-empty-string>
 */
final class NonEmptyStringType implements Type {
    /**
     * @param mixed $value
     *
     * @psalm-assert-if-true non-empty-string $value
     */
    public function matches($value): bool
    {
        return is_string($value) && $value !== '';
    }
}

/**
 * @return Type<non-empty-string>
 */
function non_empty_string(): Type {
    return new NonEmptyStringType();
}

function bar(): string { return 'hello'; }

function main(): void
{
    $value = bar();

    $type = non_empty_string();

    if ($type->matches($value)) {
        echo 'foo';
    } else {
        echo 'bar';
    }
}
```

this shouldn't fail.

**Comment by orklah** [comment]
In https://psalm.dev/r/cb32f3e4cc I think you should have typed `@psalm-assert-if-true` instead of `@psalm-assert`

**Comment by azjezz** [comment]
> In https://psalm.dev/r/cb32f3e4cc I think you should have typed @psalm-assert-if-true instead of @psalm-assert

no, i used `assert` on purpose, just to show that the issue only happens with `assert-if-*`, but not with `assert`.

**Comment by orklah** [comment]
Can you check that one again @azjezz ? I think underlying issues have been solved here
