### ISSUE TITLE
Possible regression due sprintf: TooManyArguments

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#9941]
After bumping global phar installation from v5 to master, including a cache removal, we see a 130 issues about `sprintf` in our codebase:

```
Too many arguments for the number of placeholders in sprintf (see https://psalm.dev/026)
$output->writeln(sprintf('Handling product %d => %d (%d)', $productId,  $categoryId, $position));
```

**Comment by ro0NL** [comment]
Sadly no

**Comment by orklah** [comment]
Can you tell us in which PHP version you use to run Psalm (the runtime version, not the analysis version)

cc @kkmuffme

**Comment by ro0NL** [comment]
right, both php 7.4 still

**Comment by orklah** [comment]
Note: I also reproduce on my work codebase on PHP 7.4. Seems like detection based on sprintf return is broken before PHP 8
